[package]
name = "coro-demo"
version = "0.1.0"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]

[[bin]]
name = "coro-demo"

[dependencies]
coroutine = "*"
num_cpus = "*"
deque = "*"
log = "*"
env_logger = "*"
#mio = "*"
lazy_static = "*"

#[dependencies.deque]
#path = "/Users/zonyitoo/Projects/deque"

[dependencies.mio]
git = "https://github.com/carllerche/mio.git"
#path = "/Users/zonyitoo/Projects/mio"
